export default function About() {
    return (
        <div>
            <h1>
                About
            </h1>
            <h2>
                hey
            </h2>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
            <h1>
                About
            </h1>
        </div>
    )
}